# Generated by Django 4.1.7 on 2023-03-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0014_customuser_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
